  hmis:
    - hmi_name: "HMI 0"
      hmi_id: 0
      slave_tcp:
        host: 0.0.0.0  # localhost for ROS working as HMI slave
        port: 8845  # 502 is the standard
        offset: 0
  coil_registers:  # default value to 0
    - name: "open_local_window_1_1"
      address: 0
    - name: "enter_screen_5_0"
      address: 1
    - name: "action_turn_on_pumping_process"
      address: 2
    - name: "action_recycle"
      address: 3
    - name: "enter_screen_3_0"
      address: 4
    - name: "close_local_window_0_1"
      address: 5
    - name: "enter_screen_2_0"
      address: 6
    - name: "enter_screen_4_0"
      address: 7
    - name: "enter_screen_1_0"
      address: 8
    - name: "button_lock_password"
      address: 9
    - name: "button_load_password"
      address: 10
    - name: "not_used"
      address: 11
    - name: "open_local_window_0_2"
      address: 12
    - name: "close_local_window_0_2"
      address: 13
    - name: "action_pre_fill_line"
      address: 14
    - name: "action_pull_down_pistons_manual"
      address: 15
    - name: "action_pull_up_pistons_manual"
      address: 16
    - name: "action_vacuum_air"
      address: 17
    - name: "action_depressurize"
      address: 18
    - name: "open_local_window_1_1"
      address: 19
    - name: "enter_screen_3_0"
      address: 20
    - name: "enter_screen_0_0"
      address: 21
    - name: "action_recycle_car"
      address: 22
    - name: "action_recycle_retractil"
      address: 23
    - name: "enter_screen_1_0"
      address: 24
    - name: "action_button_start_bucket_change_1"
      address: 25
    - name: "action_button_start_bucket_change_2"
      address: 26
    - name: "action_pull_down_pistons_bucket"
      address: 27
    - name: "action_pull_up_pistons_bucket"
      address: 28
    - name: "action_button_change_bucket_3"
      address: 29
    - name: "enter_screen_0_0"
      address: 30
    - name: "button_volume_1"
      address: 31
    - name: "button_volume_2"
      address: 32
    - name: "button_volume_3"
      address: 33
    # ------------------- STATUS
    - name: "status_alarm_pre_vacuum"
      address: 34
    - name: "status_vacuum_alarm"
      address: 35
    - name: "status_no_air_pressure"
      address: 36
    - name: "status_error_change_bucket"
      address: 37
    - name: "status_pump_no_pressure"
      address: 38
    - name: "status_pump_no_depressurized"
      address: 39
  holding_registers:
  # --------------------------------------- PARAMETERS START
    - name: "param_target_pressure_hyd_home"
      address: 40006
      data_type: "uint16"
    - name: "param_target_pressure_pistons_home"
      address: 40007
      data_type: "uint16"
    - name: "param_user_password"
      address: 40008
      data_type: "uint16"
    - name: "param_target_pressure_hyd_manual"
      address: 40009
      data_type: "uint16"
    - name: "param_target_pressure_pistons_manual"
      address: 40010
      data_type: "uint16"
    - name: "param_recycle_time_manual"
      address: 40011
      data_type: "uint16"
    - name: "param_recycle_time_cycle"
      address: 40012
      data_type: "uint16"
    - name: "param_pulse_train_selection"
      address: 40013
      data_type: "uint16"
    - name: "param_recycle_time_auto"
      address: 40014
      data_type: "uint16"
    - name: "param_vacuum_limit_high"
      address: 40015
      data_type: "uint16"
    - name: "param_pre_vacuum_limit_low"
      address: 40016
      data_type: "uint16"
    - name: "not_used"
      address: 40017
      data_type: "uint16"
    - name: "not_used"
      address: 40018
      data_type: "uint16"
    - name: "not_used"
      address: 40019
      data_type: "uint16"
    - name: "not_used"
      address: 40020
      data_type: "uint16"
    - name: "param_pulse_train_low"
      address: 40021
      data_type: "uint16"
    - name: "param_pulse_train_medium"
      address: 40022
      data_type: "uint16"
    - name: "param_pulse_train_high"
      address: 40023
      data_type: "uint16"
    - name: "param_vacuum_distance"
      address: 40024
      data_type: "uint16"
    - name: "param_security_distance"
      address: 40025
      data_type: "uint16"
    - name: "param_recycle_time"
      address: 40026
      data_type: "uint16"
    - name: "param_recycle_time_interval"  # time between recycle and recycle loop
      address: 40027
      data_type: "uint16"
    - name: "param_distance_bucket_1"
      address: 40028
      data_type: "uint16"
    - name: "param_distance_bucket_2"
      address: 40029
      data_type: "uint16"
    - name: "param_distance_bucket_3"
      address: 40030
      data_type: "uint16"
    - name: "param_max_time_pump_on"
      address: 40031
      data_type: "uint16"
    - name: "param_client_password"
      address: 40032
      data_type: "uint16"
    - name: "param_bucket_size_selection"
      address: 40033
      data_type: "uint16"
    # --------------------------------------- SENSORS START
    - name: "sensor_material_pressure"
      address: 40034
      data_type: "uint16"
    - name: "sensor_material_temperature"
      address: 40035
      data_type: "uint16"
    - name: "sensor_laser_distance"
      address: 40036
      data_type: "uint16"
    - name: "sensor_pressure_regulator_read_set"
      address: 40037
      data_type: "uint16"
    - name: "sensor_pressure_regulator_read_real"
      address: 40038
      data_type: "uint16"
    - name: "sensor_pressure_regulator_valve_read_state"
      address: 40039
      data_type: "uint16"
