holding_registers:
    - name: "sensor_material_pressure"
      address: 1002
      words: 1
      data_type: "uint16"
      value: 0
    - name: "sensor_material_temperature"
      address: 1003
      words: 1
      data_type: "uint16"
      value: 0
    - name: "sensor_laser_distance"
      address: 2002
      words: 1
      data_type: "uint16"
      value: 0
    - name: "sensor_pressure_regulator_read_set"
      address: 3002
      words: 1
      data_type: "uint16"
      value: 0
    - name: "sensor_pressure_regulator_real"
      address: 3003
      words: 1
      data_type: "uint16"
      value: 0
    - name: "sensor_pressure_regulator_valve_state"
      address: 3004
      words: 1
      data_type: "uint16"
      value: 0
    - name: "sensor_pressure_regulator_write_set"
      address: 3052
      words: 1
      data_type: "uint16"
      value: 0
    - name: "sensor_pressure_regulator_activate_valve"
      address: 3053
      words: 1
      data_type: "uint16"
      value: 0
    - name: "manifold"
      address: 5052
      words: 1
      data_type: "uint16"
      value: 0
    - name: "status_tower"
      address: 6060
      words: 1
      data_type: "uint16"
      value: 0
iolinks:
  -   name: "master io link 0"
      hmi_id: 0
      hmi_name: "HMI 0"
      host: 192.168.0.21
      port: 502
      framer: "socket"
      timeout_seconds: 10
      offset: -1
