  slaves:
    - name: "HMI 0"
      id: 0
      host: 0.0.0.0  # localhost for ROS working as HMI slave
      port: 8845  # 502 is the standard
      offset: 0
  coil_registers:
    - name: "enter_screen_1_0"
      address: 0
      value: 0
    - name: "open_local_window_1_1"
      address: 1
      value: 0
    - name: "open_local_window_1_2"
      address: 2
      value: 0
    - name: "open_local_window_1_3"
      address: 3
      value: 0
    - name: "close_local_window_1_1"
      address: 4
      value: 0
    - name: "close_local_window_1_2"
      address: 5
      value: 0
    - name: "close_local_window_1_3"
      address: 6
      value: 0
    - name: "enter_screen_2_0"
      address: 7
      value: 0
    - name: "turn_on_pumping_process"
      address: 8
      value: 0
    - name: "save_button"
      address: 9
      value: 0
    - name: "enter_screen_3_0"
      address: 10
      value: 0
    - name: "enter_screen_4_0"
      address: 11
      value: 0
    - name: "open_local_window_2_1"
      address: 12
      value: 0
    - name: "open_local_window_2_2"
      address: 13
      value: 0
    - name: "open_local_window_2_3"
      address: 14
      value: 0
    - name: "close_local_window_2_1"
      address: 15
      value: 0
    - name: "close_local_window_2_2"
      address: 16
      value: 0
    - name: "close_local_window_2_3"
      address: 17
      value: 0
    - name: "down_pistons"
      address: 18
      value: 0
    - name: "up_pistons"
      address: 19
      value: 0
    - name: "turn_on_pump"
      address: 20
      value: 0
    - name: "recycle"
      address: 21
      value: 0
    - name: "vacuum_air"
      address: 22
      value: 0
  holding_registers:
    - name: "param_target_pressure_hyd"
      address: 40006
      data_type: "uint16"
      value: 0
    - name: "param_target_pressure_pistons"
      address: 40007
      data_type: "uint16"
      value: 0
    - name: "param_pulse_train_low"
      address: 40008
      data_type: "uint16"
      value: 0
    - name: "param_pulse_train_medium"
      address: 40009
      data_type: "uint16"
      value: 0
    - name: "param_pulse_train_high"
      address: 40010
      data_type: "uint16"
      value: 0
    - name: "param_alarm_pre_vacuum_limit_high"
      address: 40011
      data_type: "uint16"
      value: 0
    - name: "param_alarm_pre_vacuum_limit_low"
      address: 40012
      data_type: "uint16"
      value: 0
    - name: "param_alarm_pre_vacuum_distance"
      address: 40013
      data_type: "uint16"
      value: 0
    - name: "param_security_distance"
      address: 40014
      data_type: "uint16"
      value: 0
    - name: "param_recycle_time"
      address: 40015
      data_type: "uint16"
      value: 0
    - name: "param_pulse_train_selection"
      address: 40016
      data_type: "uint16"
      value: 0
    - name: "status_general" # status registers
      address: 40017
      data_type: "uint16"
      value: 0
    - name: "status_in_process_alarm"
      address: 40018
      data_type: "uint16"
      value: 0
    - name: "status_operational_alarm"
      address: 40019
      data_type: "uint16"
      value: 0
    - name: "status_operational_state"
      address: 40020
      data_type: "uint16"
      value: 0
    - name: "status_extend_piston"
      address: 40021
      data_type: "uint16"
      value: 0
    - name: "status_retract_piston"
      address: 40022
      data_type: "uint16"
      value: 0
    - name: "status_air_vacuum"
      address: 40023
      data_type: "uint16"
      value: 0
    - name: "status_acoustic_signal"
      address: 40024
      data_type: "uint16"
      value: 0
    - name: "status_recycling"
      address: 40025
      data_type: "uint16"
      value: 0
    - name: "data_target_pressure_pistons" # data registers
      address: 40026
      data_type: "uint16"
      value: 0
    - name: "data_target_pressure_hyd"  # same as material pressure??
      address: 40027
      data_type: "uint16"
      value: 0
    - name: "data_pulse_train_low"
      address: 40028
      data_type: "uint16"
      value: 0
    - name: "data_pulse_train_medium"
      address: 40029
      data_type: "uint16"
      value: 0
    - name: "data_pulse_train_high"
      address: 40030
      data_type: "uint16"
      value: 0
    - name: "data_vacuum_limit_high"
      address: 40031
      data_type: "uint16"
      value: 0
    - name: "data_vacuum_limit_low"
      address: 40032
      data_type: "uint16"
      value: 0
    - name: "data_vacuum_distance"
      address: 40033
      data_type: "uint16"
      value: 0
    - name: "data_security_distance"
      address: 40034
      data_type: "uint16"
      value: 0
    - name: "data_pulse_train_selection"
      address: 40035
      data_type: "uint16"
      value: 0
