  slaves:
    - name: "HMI 0"
      id: 0
      host: 0.0.0.0  # localhost for ROS working as HMI slave
      port: 8845  # 502 is the standard
      offset: 0
  coil_registers:  # default value to 0
    - name: "open_local_window_1_1"
      address: 0
    - name: "enter_screen_5_0"
      address: 1
    - name: "turn_on_pumping_process"
      address: 2
    - name: "recycle"
      address: 3
    - name: "enter_screen_3_0"
      address: 4
    - name: "close_local_window_0_1"
      address: 5
    - name: "enter_screen_2_0"
      address: 6
    - name: "enter_screen_4_0"
      address: 7
    - name: "enter_screen_1_0"
      address: 8
    - name: "button_lock_password"
      address: 9
    - name: "button_load_password"
      address: 10
    - name: "open_local_window_0_2"
      address: 12  # jumped 11 - ok
    - name: "close_local_window_0_2"
      address: 13
    - name: "pre-fill-line"
      address: 14
    - name: "pull_down_pistons_manual"
      address: 15
    - name: "pull_up_pistons_manual"
      address: 16
    - name: "vacuum_air"
      address: 17
    - name: "depressurize"
      address: 18
    - name: "open_local_window_1_1"
      address: 19
    - name: "enter_screen_3_0"
      address: 20
    - name: "enter_screen_0_0"
      address: 21
    - name: "recycle_car"
      address: 22
    - name: "recycle_retractil"
      address: 23
    - name: "enter_screen_1_0"
      address: 24
    - name: "button_start_bucket_change_1"
      address: 25
    - name: "button_start_bucket_change_2"
      address: 26
    - name: "pull_down_pinstons_bucket"
      address: 27
    - name: "pull_up_pinstons_bucket"
      address: 28
    - name: "button_change_bucket_3"
      address: 29
    - name: "enter_screen_0_0"
      address: 30
    - name: "button_volume_1"
      address: 31
    - name: "button_volume_2"
      address: 32
    - name: "button_volume_3"
      address: 33
  holding_registers:
    - name: "param_target_pressure_hyd"
      address: 40006
      data_type: "uint16"
      value: 0
    - name: "param_target_pressure_pistons"
      address: 40007
      data_type: "uint16"
      value: 0
    - name: "param_pulse_train_low"
      address: 40008
      data_type: "uint16"
      value: 0
    - name: "param_pulse_train_medium"
      address: 40009
      data_type: "uint16"
      value: 0
    - name: "param_pulse_train_high"
      address: 40010
      data_type: "uint16"
      value: 0
    - name: "param_alarm_pre_vacuum_limit_high"
      address: 40011
      data_type: "uint16"
      value: 0
    - name: "param_alarm_pre_vacuum_limit_low"
      address: 40012
      data_type: "uint16"
      value: 0
    - name: "param_alarm_pre_vacuum_distance"
      address: 40013
      data_type: "uint16"
      value: 0
    - name: "param_security_distance"
      address: 40014
      data_type: "uint16"
      value: 0
    - name: "param_recycle_time"
      address: 40015
      data_type: "uint16"
      value: 0
    - name: "param_pulse_train_selection"
      address: 40016
      data_type: "uint16"
      value: 0
    - name: "status_general" # status registers
      address: 40017
      data_type: "uint16"
      value: 0
    - name: "status_in_process_alarm"
      address: 40018
      data_type: "uint16"
      value: 0
    - name: "status_operational_alarm"
      address: 40019
      data_type: "uint16"
      value: 0
    - name: "status_operational_state"
      address: 40020
      data_type: "uint16"
      value: 0
    - name: "status_extend_piston"
      address: 40021
      data_type: "uint16"
      value: 0
    - name: "status_retract_piston"
      address: 40022
      data_type: "uint16"
      value: 0
    - name: "status_air_vacuum"
      address: 40023
      data_type: "uint16"
      value: 0
    - name: "status_acoustic_signal"
      address: 40024
      data_type: "uint16"
      value: 0
    - name: "status_recycling"
      address: 40025
      data_type: "uint16"
      value: 0
    - name: "data_target_pressure_pistons" # data registers
      address: 40026
      data_type: "uint16"
      value: 0
    - name: "data_target_pressure_hyd"  # same as material pressure??
      address: 40027
      data_type: "uint16"
      value: 0
    - name: "data_pulse_train_low"
      address: 40028
      data_type: "uint16"
      value: 0
    - name: "data_pulse_train_medium"
      address: 40029
      data_type: "uint16"
      value: 0
    - name: "data_pulse_train_high"
      address: 40030
      data_type: "uint16"
      value: 0
    - name: "data_vacuum_limit_high"
      address: 40031
      data_type: "uint16"
      value: 0
    - name: "data_vacuum_limit_low"
      address: 40032
      data_type: "uint16"
      value: 0
    - name: "data_vacuum_distance"
      address: 40033
      data_type: "uint16"
      value: 0
    - name: "data_security_distance"
      address: 40034
      data_type: "uint16"
      value: 0
    - name: "data_pulse_train_selection"
      address: 40035
      data_type: "uint16"
      value: 0
    - name: "sensor_material_pressure"
      address: 40036
      data_type: "uint16"
      value: 0
    - name: "sensor_material_temperature"
      address: 40037
      data_type: "uint16"
      value: 0
    - name: "sensor_laser_distance"
      address: 40038
      data_type: "uint16"
      value: 0
    - name: "sensor_pressure_regulator_read_set"
      address: 40039
      data_type: "uint16"
      value: 0
    - name: "sensor_pressure_regulator_read_real"
      address: 40040
      data_type: "uint16"
      value: 0
    - name: "sensor_pressure_regulator_valve_read_state"
      address: 40041
      data_type: "uint16"
      value: 0
