  slaves:
    - name: "HMI 1"
      id: 0
      host: 0.0.0.0  # this will be the HMI's IP
      port: 502  # 502 is the standard
      offset: 0
  holding_registers:
    - name: "param_target_pressure_pistons"
      address: 40001
      data_type: "uint16"
      value: 0
    - name: "param_target_pressure_material"
      address: 40002
      data_type: "uint16"
      value: 0
    - name: "param_system_state"
      address: 40003
      data_type: "uint16"
      value: 0
    - name: "param_pulse_train_high"
      address: 40004
      data_type: "uint16"
      value: 0
    - name: "param_pulse_train_medium"
      address: 40005
      data_type: "uint16"
      value: 0
    - name: "param_pulse_train_low"
      address: 40006
      data_type: "uint16"
      value: 0
    - name: "param_emergency_stop_state"
      address: 40007
      data_type: "uint16"
      value: 0
    - name: "param_solenoid_valves_state"
      address: 40008
      data_type: "uint16"
      value: 0
    - name: "param_alarm_state"
      address: 40009
      data_type: "uint16"
      value: 0
    - name: "param_alarm_pre_vacuum_limit_high"
      address: 40010
      data_type: "uint16"
      value: 0
    - name: "param_alarm_pre_vacuum_limit_low"
      address: 40011
      data_type: "uint16"
      value: 0
    - name: "param_alarm_pre_vacuum_distance"
      address: 40012
      data_type: "uint16"
      value: 0
    - name: "sensor_material_pressure"
      address: 40013
      data_type: "uint16"
      value: 0
    - name: "sensor_material_temperature"
      address: 40014
      data_type: "uint16"
      value: 0
    - name: "sensor_laser_distance"
      address: 40015
      data_type: "uint16"
      value: 0
