holding_registers:
    - name: "sensor_material_pressure"
      address: 1002
      words: 1
      data_type: "uint16"
      mode: "r"
    - name: "sensor_material_temperature"
      address: 1003
      words: 1
      data_type: "uint16"
      mode: "r"
    - name: "sensor_laser_distance"
      address: 2002
      words: 1
      data_type: "uint16"
      mode: "r"
    - name: "sensor_pressure_regulator_read_set"
      address: 3002
      words: 1
      data_type: "uint16"
      mode: "r"
    - name: "sensor_pressure_regulator_read_real"
      address: 3003
      words: 1
      data_type: "uint16"
      mode: "r"
    - name: "sensor_pressure_regulator_valve_read_state"  # all sensors are read
      address: 3004
      words: 1
      data_type: "uint16"
      mode: "r"
    - name: "param_regulator_pressure_set"
      address: 3052
      words: 1
      data_type: "uint16"
      mode: "w"
    - name: "regulator_activate_valve"
      address: 3053
      words: 1
      data_type: "uint16"
      mode: "w"
    - name: "action_manifold"
      address: 5051
      words: 1
      data_type: "uint16"
      mode: "w"
    - name: "digital_in_emergency_stop"
      address: 4002
      words: 1
      data_type: "uint16"
      mode: "r"
    - name: "digital_out_hyd_valve"
      address: 7051
      words: 1
      data_type: "uint16"
      mode: "w"
iolinks:
  - name: "master io link 0"
    hmi_id: 0
    hmi_name: "HMI 0"
    slave_tcp:
      host: 192.168.0.21
      port: 502
      framer: "socket"
      timeout_seconds: 1
      offset: -1
